// Generated from localization/zh_CN.tsv. SPDX-License-Identifier: GPL-3.0-or-later
#pragma once
struct ZhTerm { const char *english; const char *chinese; };
static const ZhTerm zh_terms[] = {
    {"mister by alexey melnikov, based on mist by till harbaum, minimig by dennis van weeren and other projects. mister hardware and software is distributed under the terms of the gnu general public license version 3. mister fpga cores are the work of their respective authors under individual licensing. go to www.misterfpga.org for more details.", u8"MiSTer 由 Alexey Melnikov 开发，基于 Till Harbaum 的 MiST、Dennis van Weeren 的 Minimig 等项目。MiSTer 软硬件采用 GNU GPL 第3版许可；各 FPGA 核心由其作者按各自许可发布。详情：www.MiSTerFPGA.org。"},
    {"welcome to mister! use the cursor keys to navigate the menus. use space bar or enter to select an item. press esc or f12 to exit the menus. joystick emulation on the numeric keypad can be toggled with the numlock or scrlock key, while pressing ctrl-alt-0 (numeric keypad) toggles autofire mode.", u8"欢迎使用 MiSTer！用方向键浏览，空格或回车选择，Esc 或 F12 退出。NumLock 或 ScrollLock 切换小键盘摇杆模拟；Ctrl+Alt+小键盘0 切换连发。"},
    {"minimig can make use of up to 2 megabytes of chip ram, up to 1.5 megabytes of slow ram (a500 trapdoor ram), and up to 384 megabytes of fast ram (8mb max for 68000 mode). to use the hrtmon feature you will need a file on the sd card named hrtmon.rom.", u8"Minimig 支持最多2MB芯片内存、1.5MB慢速内存及384MB快速内存（68000模式最多8MB）。使用 HRTmon 需要 SD 卡上的 hrtmon.rom 文件。"},
    {"minimig can emulate an a600/a1200 ide harddisk interface. the emulation can make use of minimig-style hardfiles (complete disk images) or uae-style hardfiles (filesystem images with no partition table).", u8"Minimig 可模拟 A600/A1200 的 IDE 硬盘接口，支持 Minimig 完整磁盘镜像和 UAE 无分区表的文件系统镜像。"},
    {"minimig's processor core can emulate a 68000 (cycle accuracy as a500/a600) or 68020 (maximum performance) processor with transparent cache.", u8"Minimig 可模拟 68000（A500/A600 周期精确）或 68020（高性能）处理器，并提供透明缓存。"},
    {"backspace key (or b-hold + a on gamepad) to clear stored option. you have to reload the core to be able to use default value.", u8"按退格键，或手柄按住B再按A，清除已存选项。重新加载核心后使用默认值。"},
    {"backspace key (or b-hold + a on gamepad) to unmount", u8"按退格键，或手柄按住B再按A，卸载镜像。"},
    {"invalid cheat code! disabling cheats.", u8"金手指代码无效，已禁用。"},
    {"failed to initialize cheat engine!", u8"金手指引擎初始化失败！"},
    {"this is dangerous operation!", u8"此操作存在风险！"},
    {"this joystick is not defined", u8"此手柄尚未设置"},
    {"joystick in menu core first", u8"中设置此手柄"},
    {"kp +/- to add/remove drives", u8"小键盘 +/- 增减软驱"},
    {"no usb found, using sd card", u8"未找到USB，使用SD卡"},
    {"script has control over the", u8"脚本能控制整个系统，"},
    {"sd card and fill with files", u8"才能恢复使用。"},
    {"select drive to toggle mode", u8"选择软驱以切换模式"},
    {"the files or settings, then", u8"导致 MiSTer 无法启动。"},
    {"unsupported cartridge type!", u8"不支持的卡带类型！"},
    {"whole system and may damage", u8"可能损坏文件或设置，"},
    {"you have to reload the core", u8"请重新加载核心"},
    {"button(s)/key(s) -> key(s)", u8"按键组合 → 键盘键"},
    {"either disable framebuffer", u8"可关闭帧缓冲"},
    {"graphics will be corrupted", u8"画面可能损坏"},
    {"will have to re-format the", u8"SD 卡并重新复制文件，"},
    {"cannot open bsx_bios.rom!", u8"无法打开 bsx_bios.rom！"},
    {"if you see this, then you", u8"如果看到此提示，请"},
    {"in order to use it again.", u8"请确认后再继续。"},
    {"mister won't boot, so you", u8"届时需要重新格式化"},
    {"need to modify mister.ini", u8"修改 MiSTer.ini"},
    {"press button(s) on joypad", u8"按手柄上的按键"},
    {"press button(s) to map to", u8"按目标手柄键"},
    {"use dpad/cursor to select", u8"用方向键选择"},
    {"(can use 2-button combo)", u8"（可用双键组合）"},
    {"do you want to continue?", u8"是否继续？"},
    {"finish screen adjustment", u8"完成画面调整"},
    {"screen and press trigger", u8"并扣动扳机"},
    {"stick 1 test: tilt right", u8"摇杆1测试：向右推"},
    {"stick 2 test: tilt right", u8"摇杆2测试：向右推"},
    {"yes, and don't ask again", u8"是，不再询问"},
    {"cannot open goomba.rom!", u8"无法打开 goomba.rom！"},
    {"define joystick buttons", u8"设置手柄按键"},
    {"esc clear, enter finish", u8"Esc 清除，回车完成"},
    {"mouse emu x: tilt right", u8"鼠标横轴：向右推"},
    {"or enable scaler on vga", u8"或启用 VGA 缩放器"},
    {"or key(s) on a keyboard", u8"或按键盘上的键"},
    {"press any key to cancel", u8"按任意键取消"},
    {"reset player assignment", u8"重置玩家分配"},
    {"stick 1 test: tilt down", u8"摇杆1测试：向下推"},
    {"stick 2 test: tilt down", u8"摇杆2测试：向下推"},
    {"you need to define this", u8"请先在主菜单核心"},
    {"adjust screen position", u8"调整画面位置"},
    {"button(s) -> button(s)", u8"手柄键 → 手柄键"},
    {"delete all pairings...", u8"删除全部配对…"},
    {"dpad test: press right", u8"方向键测试：按右"},
    {"mouse emu y: tilt down", u8"鼠标纵轴：向下推"},
    {"no bluetooth available", u8"没有可用的蓝牙设备"},
    {"press key(s) to map to", u8"按目标键盘键"},
    {"unable to read header!", u8"无法读取文件头！"},
    {"dpad test: press down", u8"方向键测试：按下"},
    {"light gun mode is off", u8"光枪模式已关闭"},
    {"not a m/code program!", u8"不是机器码程序！"},
    {"or key(s) on keyboard", u8"或按键盘上的键"},
    {"press keyboard key(s)", u8"按键盘按键"},
    {"reset uart connection", u8"重置串口连接"},
    {"scaler not compatible", u8"缩放器不兼容"},
    {"to use default value.", u8"以使用默认值。"},
    {"alternative buttons?", u8"备用按键？"},
    {"clearing the recents", u8"正在清除最近记录"},
    {"do you want to setup", u8"是否设置"},
    {"kbd mode: joystick 1", u8"键盘模式：摇杆1"},
    {"kbd mode: joystick 2", u8"键盘模式：摇杆2"},
    {"light gun mode is on", u8"光枪模式已开启"},
    {"lightgun calibration", u8"光枪校准"},
    {"point to the edge of", u8"瞄准屏幕边缘"},
    {"queue limit reached!", u8"队列已满！"},
    {"unable to open file!", u8"无法打开文件！"},
    {"unmounting the image", u8"正在卸载镜像"},
    {"clearing the option", u8"正在清除选项"},
    {"or key(s) to change", u8"或键盘键进行修改"},
    {"press key to change", u8"按键进行修改"},
    {"reset and close osd", u8"重启并关闭菜单"},
    {"reset hanging notes", u8"清除挂起音符"},
    {"stick 1: tilt right", u8"摇杆1：向右推"},
    {"user/space undefine", u8"用户键／空格取消定义"},
    {"active after reset", u8"重启后生效"},
    {"add from main menu", u8"从主菜单添加"},
    {"cd bios not found!", u8"未找到光驱 BIOS！"},
    {"failed to load rom", u8"加载 ROM 失败"},
    {"load configuration", u8"加载配置"},
    {"load direct to ram", u8"直接加载到内存"},
    {"map header (ascii)", u8"映射头部（ASCII）"},
    {"not enough memory!", u8"内存不足！"},
    {"save configuration", u8"保存配置"},
    {"select memory bank", u8"选择内存区"},
    {"stick 1: tilt down", u8"摇杆1：向下推"},
    {"user/menu undefine", u8"用户键／菜单取消定义"},
    {"cart image saved.", u8"卡带镜像已保存。"},
    {"enable custom rom", u8"启用自定义 ROM"},
    {"enter unlock code", u8"输入解锁码"},
    {"missing directory", u8"目录不存在"},
    {"not a valid tape!", u8"无效的磁带！"},
    {"reset to defaults", u8"恢复默认设置"},
    {"screenshot failed", u8"截图失败"},
    {"spinner: disabled", u8"旋钮已禁用"},
    {"supported mapping", u8"支持的映射"},
    {"switch to sd card", u8"切换到 SD 卡"},
    {"button/key remap", u8"重新映射按键"},
    {"change soundfont", u8"更换音色库"},
    {"ctrl+esc to exit", u8"Ctrl+Esc 退出"},
    {"external drive 2", u8"外部软驱2"},
    {"external drive 3", u8"外部软驱3"},
    {"fast-ide (68020)", u8"高速 IDE（68020）"},
    {"gamma correction", u8"伽马校正"},
    {"kbd mode: normal", u8"键盘模式：正常"},
    {"lcd-auto(non-fb)", u8"LCD自动（无帧缓冲）"},
    {"menu-hold cancel", u8"长按菜单键取消"},
    {"mouse btn middle", u8"鼠标中键"},
    {"mouse emu/sniper", u8"鼠标模拟／精确模式"},
    {"mouse move right", u8"鼠标右移"},
    {"ok-hold advanced", u8"长按确认进入高级设置"},
    {"physical drive 2", u8"实体软驱2"},
    {"physical drive 3", u8"实体软驱3"},
    {"press key to map", u8"按键以映射"},
    {"reset to default", u8"恢复默认值"},
    {"saving the state", u8"正在保存状态"},
    {"screenshot saved", u8"截图已保存"},
    {"spinner: enabled", u8"旋钮已启用"},
    {"storage: sd card", u8"存储：SD卡"},
    {"video processing", u8"视频处理"},
    {"visible 216p(5x)", u8"可视区216p（5倍）"},
    {"write protection", u8"写保护"},
    {"25mhz audio fix", u8"25MHz 音频修正"},
    {"autofire medium", u8"中速连发"},
    {"available space", u8"可用空间"},
    {"clear the list?", u8"清空列表？"},
    {"floppy disk rom", u8"软驱 ROM"},
    {"input hotkey(s)", u8"输入快捷键"},
    {"kbd mode: mouse", u8"键盘模式：鼠标"},
    {"low pass filter", u8"低通滤波"},
    {"menu-hold clear", u8"长按菜单键清除"},
    {"monitor (40x25)", u8"监控程序（40×25）"},
    {"monitor (80x25)", u8"监控程序（80×25）"},
    {"mouse btn right", u8"鼠标右键"},
    {"mouse move down", u8"鼠标下移"},
    {"mouse move left", u8"鼠标左移"},
    {"on any keyboard", u8"可使用任意键盘"},
    {"on the same pad", u8"在同一手柄上操作"},
    {"press button(s)", u8"按手柄按键"},
    {"press esc/enter", u8"按 Esc／回车"},
    {"reset and apply", u8"重启并应用"},
    {"reset and close", u8"重启并关闭"},
    {"reset settings?", u8"重置设置？"},
    {"screen rotation", u8"画面旋转"},
    {"space/user skip", u8"空格／用户键跳过"},
    {"start cd32 game", u8"启动 CD32 游戏"},
    {"start cdtv game", u8"启动 CDTV 游戏"},
    {"system settings", u8"系统设置"},
    {"audio settings", u8"音频设置"},
    {"cartridge type", u8"卡带类型"},
    {"char generator", u8"字符发生器"},
    {"core button(s)", u8"核心按键"},
    {"current config", u8"当前配置"},
    {"default config", u8"默认配置"},
    {"define buttons", u8"设置按键"},
    {"external drive", u8"外部软驱"},
    {"fast tape load", u8"磁带快速加载"},
    {"floppy storage", u8"软盘存储"},
    {"joysticks swap", u8"交换摇杆"},
    {"lcd-on(non-fb)", u8"LCD常亮（无帧缓冲）"},
    {"load cartridge", u8"加载卡带"},
    {"lowpass filter", u8"低通滤波"},
    {"mouse btn left", u8"鼠标左键"},
    {"mouse mode off", u8"鼠标模式已关闭"},
    {"physical drive", u8"实体软驱"},
    {"remap keyboard", u8"重新映射键盘"},
    {"reset minimig?", u8"重启 Minimig？"},
    {"reset settings", u8"重置设置"},
    {"reset to apply", u8"重启后生效"},
    {"rom management", u8"ROM 管理"},
    {"scandoubler fx", u8"倍线效果"},
    {"sprite flicker", u8"精灵闪烁"},
    {"startup config", u8"启动配置"},
    {"swap joysticks", u8"交换摇杆"},
    {"uart baud rate", u8"串口波特率"},
    {"video settings", u8"视频设置"},
    {"5-button mode", u8"5键模式"},
    {"8-button mode", u8"8键模式"},
    {"audio & video", u8"音频与视频"},
    {"autofire fast", u8"快速连发"},
    {"autofire slow", u8"慢速连发"},
    {"compatibility", u8"兼容性"},
    {"cpu frequency", u8"CPU 频率"},
    {"enable cheats", u8"启用金手指"},
    {"expansion ram", u8"扩展内存"},
    {"f12 clear all", u8"F12 清除全部"},
    {"global volume", u8"全局音量"},
    {"graphics addr", u8"图形地址"},
    {"help requires", u8"帮助功能需要"},
    {"interpolation", u8"插值"},
    {"invincibility", u8"无敌"},
    {"joystick swap", u8"交换摇杆"},
    {"joystick type", u8"摇杆类型"},
    {"machine model", u8"机器型号"},
    {"misc. options", u8"其他选项"},
    {"modify config", u8"修改配置"},
    {"mouse mode on", u8"鼠标模式已开启"},
    {"mouse move up", u8"鼠标上移"},
    {"nearneighbour", u8"最近邻"},
    {"no rbf found!", u8"未找到核心文件！"},
    {"not detected!", u8"未检测到！"},
    {"on a keyboard", u8"在键盘上操作"},
    {"other configs", u8"其他配置"},
    {"reload config", u8"重新加载配置"},
    {"rotate screen", u8"旋转画面"},
    {"rtg upscaling", u8"RTG 放大"},
    {"save settings", u8"保存设置"},
    {"space to exit", u8"空格退出"},
    {"switch to usb", u8"切换到 USB"},
    {"user undefine", u8"用户键取消定义"},
    {"video area by", u8"画面区域依据"},
    {"vram cpu wait", u8"显存 CPU 等待"},
    {"write protect", u8"写保护"},
    {"aspect ratio", u8"画面比例"},
    {"audio filter", u8"音频滤波"},
    {"audio source", u8"音频来源"},
    {"autofire off", u8"关闭连发"},
    {"cold reboot)", u8"冷启动）"},
    {"dip switches", u8"拨码开关"},
    {"display type", u8"显示类型"},
    {"enter finish", u8"回车完成"},
    {"f12 advanced", u8"F12 高级设置"},
    {"not charging", u8"未充电"},
    {"not detected", u8"未检测到"},
    {"not selected", u8"未选择"},
    {"paula output", u8"Paula 输出"},
    {"reboot (hold", u8"重启（长按"},
    {"recent cores", u8"最近使用的核心"},
    {"recent files", u8"最近使用的文件"},
    {"refresh rate", u8"刷新率"},
    {"removable/cd", u8"可移动／光驱"},
    {"reset config", u8"重置配置"},
    {"same as horz", u8"同水平滤波"},
    {"same as vert", u8"同垂直滤波"},
    {"scan doubler", u8"倍线器"},
    {"screen: mono", u8"屏幕：单色"},
    {"service mode", u8"维修模式"},
    {"signal block", u8"信号块"},
    {"sprite limit", u8"精灵数量限制"},
    {"storage: usb", u8"存储：USB"},
    {"swap btn 2/3", u8"交换按键2/3"},
    {"swap buttons", u8"交换按键"},
    {"tape buttons", u8"磁带按键"},
    {"tape details", u8"磁带详情"},
    {"tape storage", u8"磁带存储"},
    {"video filter", u8"视频滤波"},
    {"a(red/fire)", u8"A（红色／开火）"},
    {"button swap", u8"交换按键"},
    {"cheat codes", u8"金手指代码"},
    {"clear queue", u8"清空队列"},
    {"cold reboot", u8"冷启动"},
    {"controllers", u8"控制器"},
    {"core volume", u8"核心音量"},
    {"demo sounds", u8"演示音效"},
    {"flip screen", u8"翻转画面"},
    {"floppy disk", u8"软盘"},
    {"full screen", u8"全屏"},
    {"horz filter", u8"水平滤波"},
    {"hv-integer+", u8"整数缩放（大）"},
    {"hv-integer-", u8"整数缩放（小）"},
    {"information", u8"信息"},
    {"intl filter", u8"隔行滤波"},
    {"key mapping", u8"按键映射"},
    {"load config", u8"加载配置"},
    {"load preset", u8"加载预设"},
    {"low latency", u8"低延迟"},
    {"memory dump", u8"内存转储"},
    {"memory size", u8"内存大小"},
    {"menu finish", u8"菜单键完成"},
    {"on keyboard", u8"键盘"},
    {"orientation", u8"方向"},
    {"paddle mode", u8"拨盘模式"},
    {"pixel clock", u8"像素时钟"},
    {"queue error", u8"队列错误"},
    {"sample freq", u8"采样频率"},
    {"save config", u8"保存配置"},
    {"scan filter", u8"扫描线滤波"},
    {"scandoubler", u8"倍线器"},
    {"shadow mask", u8"荫罩"},
    {"tape queued", u8"磁带已入队"},
    {"tv standard", u8"电视制式"},
    {"use mt32-pi", u8"使用 MT32-pi"},
    {"vert filter", u8"垂直滤波"},
    {"vga scaling", u8"VGA 缩放"},
    {"1x rotated", u8"1倍旋转"},
    {"2x rotated", u8"2倍旋转"},
    {"background", u8"背景"},
    {"bonus life", u8"奖励生命"},
    {"boot order", u8"启动顺序"},
    {"boot reset", u8"启动重置"},
    {"brightness", u8"亮度"},
    {"bt pairing", u8"蓝牙配对"},
    {"cd32 drive", u8"CD32 光驱"},
    {"cdtv drive", u8"CDTV 光驱"},
    {"connection", u8"连接"},
    {"controller", u8"控制器"},
    {"debug leds", u8"调试指示灯"},
    {"debug mode", u8"调试模式"},
    {"difficulty", u8"难度"},
    {"disk image", u8"磁盘镜像"},
    {"drive type", u8"软驱类型"},
    {"eject disk", u8"弹出磁盘"},
    {"esc cancel", u8"Esc 取消"},
    {"foreground", u8"前景"},
    {"horizontal", u8"水平"},
    {"hv-integer", u8"横纵整数缩放"},
    {"kbd toggle", u8"切换键盘"},
    {"load state", u8"加载状态"},
    {"loading...", u8"正在加载…"},
    {"menu: back", u8"菜单：返回"},
    {"mount disk", u8"挂载磁盘"},
    {"no network", u8"未连接网络"},
    {"queue tape", u8"加入磁带队列"},
    {"read/write", u8"读写"},
    {"saturation", u8"饱和度"},
    {"save state", u8"保存状态"},
    {"select ini", u8"选择配置文件"},
    {"set hotkey", u8"设置快捷键"},
    {"sound chip", u8"音频芯片"},
    {"sound mode", u8"声音模式"},
    {"stereo mix", u8"立体声混合"},
    {"tape error", u8"磁带错误"},
    {"to confirm", u8"以确认"},
    {"usb serial", u8"USB 串口"},
    {"video crop", u8"画面裁切"},
    {"video mode", u8"视频模式"},
    {"warning!!!", u8"警告！"},
    {"a: and b:", u8"A: 和 B:"},
    {"attention", u8"注意"},
    {"auto(led)", u8"自动（LED）"},
    {"boot mode", u8"启动模式"},
    {"c(yellow)", u8"C（黄色）"},
    {"canceling", u8"正在取消"},
    {"cold boot", u8"冷启动"},
    {"configure", u8"配置"},
    {"cpu cache", u8"CPU 缓存"},
    {"cpu speed", u8"CPU 速度"},
    {"cpu turbo", u8"CPU 加速"},
    {"emulation", u8"模拟"},
    {"esc clear", u8"Esc 清除"},
    {"exec addr", u8"执行地址"},
    {"expansion", u8"扩展"},
    {"fdd turbo", u8"软驱加速"},
    {"file name", u8"文件名"},
    {"file size", u8"文件大小"},
    {"file type", u8"文件类型"},
    {"finishing", u8"正在完成"},
    {"fixed/hdd", u8"固定／硬盘"},
    {"free play", u8"免费游玩"},
    {"frequency", u8"频率"},
    {"from file", u8"来自文件"},
    {"hard disk", u8"硬盘"},
    {"load addr", u8"加载地址"},
    {"load bios", u8"加载 BIOS"},
    {"load tape", u8"加载磁带"},
    {"main menu", u8"主菜单"},
    {"mono 60hz", u8"单色60Hz"},
    {"no files!", u8"没有文件！"},
    {"output(s)", u8"输出按键"},
    {"overclock", u8"超频"},
    {"read only", u8"只读"},
    {"saving...", u8"正在保存…"},
    {"scanlines", u8"扫描线"},
    {"show info", u8"显示信息"},
    {"soundfont", u8"音色库"},
    {"test mode", u8"测试模式"},
    {"uart mode", u8"串口模式"},
    {"unlimited", u8"无限"},
    {"user port", u8"用户接口"},
    {"v-integer", u8"纵向整数缩放"},
    {"<up-dir>", u8"<上级>"},
    {"accurate", u8"精确"},
    {"adaptive", u8"自适应"},
    {"advanced", u8"高级设置"},
    {"autofire", u8"连发"},
    {"autosave", u8"自动保存"},
    {"bilinear", u8"双线性"},
    {"boot rom", u8"启动 ROM"},
    {"bootcore", u8"启动核心"},
    {"button a", u8"按键 A"},
    {"button b", u8"按键 B"},
    {"button l", u8"按键 L"},
    {"button r", u8"按键 R"},
    {"button x", u8"按键 X"},
    {"button y", u8"按键 Y"},
    {"canceled", u8"已取消"},
    {"cd & hdd", u8"光驱与硬盘"},
    {"clearing", u8"正在清除"},
    {"cocktail", u8"桌式"},
    {"continue", u8"继续"},
    {"contrast", u8"对比度"},
    {"controls", u8"控制设置"},
    {"cpu mode", u8"CPU 模式"},
    {"cpu type", u8"CPU 类型"},
    {"d(green)", u8"D（绿色）"},
    {"disabled", u8"已禁用"},
    {"ethernet", u8"以太网"},
    {"floppy 0", u8"软驱0"},
    {"floppy 1", u8"软驱1"},
    {"graphics", u8"图形"},
    {"infinite", u8"无限"},
    {"internal", u8"内部"},
    {"japanese", u8"日文"},
    {"joystick", u8"摇杆"},
    {"keyboard", u8"键盘"},
    {"language", u8"语言"},
    {"load rom", u8"加载 ROM"},
    {"lock osd", u8"锁定菜单"},
    {"menu: ok", u8"菜单：确认"},
    {"mount *.", u8"挂载 *."},
    {"munt rom", u8"Munt 固件"},
    {"original", u8"原始"},
    {"overscan", u8"过扫描"},
    {"pcg mode", u8"PCG 模式"},
    {"position", u8"位置"},
    {"ram size", u8"内存大小"},
    {"rotation", u8"旋转"},
    {"save ram", u8"保存存档内存"},
    {"settings", u8"设置"},
    {"standard", u8"标准"},
    {"user rom", u8"用户 ROM"},
    {"variable", u8"可变"},
    {"vertical", u8"垂直"},
    {"written!", u8"已写入！"},
    {"ym-audio", u8"YM 音频"},
    {"b(blue)", u8"B（蓝色）"},
    {"blitter", u8"位块传送器"},
    {"borders", u8"边框"},
    {"buttons", u8"按键"},
    {"cabinet", u8"机柜"},
    {"chinese", u8"中文"},
    {"chipram", u8"芯片内存"},
    {"chipset", u8"芯片组"},
    {"coinage", u8"投币设置"},
    {"console", u8"控制台"},
    {"d-cache", u8"数据缓存"},
    {"default", u8"默认"},
    {"digital", u8"数字"},
    {"disable", u8"禁用"},
    {"display", u8"显示"},
    {"dump to", u8"转储到"},
    {"enabled", u8"已启用"},
    {"english", u8"英文"},
    {"ext.rom", u8"扩展 ROM"},
    {"fastram", u8"快速内存"},
    {"flicker", u8"闪烁"},
    {"forward", u8"向前"},
    {"hardest", u8"最难"},
    {"integer", u8"整数"},
    {"latency", u8"延迟"},
    {"load *.", u8"加载 *."},
    {"machine", u8"机型"},
    {"nearest", u8"最近邻"},
    {"no disk", u8"未插入磁盘"},
    {"no info", u8"无信息"},
    {"options", u8"选项"},
    {"palette", u8"调色板"},
    {"reverse", u8"反向"},
    {"scaling", u8"缩放"},
    {"scripts", u8"脚本"},
    {"service", u8"维修"},
    {"signals", u8"信号"},
    {"slowram", u8"慢速内存"},
    {"sprites", u8"精灵"},
    {"test sb", u8"测试信号块"},
    {"unknown", u8"未知"},
    {"upright", u8"直立式"},
    {"visible", u8"可视区"},
    {"a only", u8"仅 A"},
    {"active", u8"已启用"},
    {"analog", u8"模拟"},
    {"aspect", u8"画面比例"},
    {"b only", u8"仅 B"},
    {"blank+", u8"消隐+"},
    {"border", u8"边框"},
    {"cancel", u8"取消"},
    {"center", u8"居中"},
    {"cheats", u8"金手指"},
    {"colour", u8"彩色"},
    {"config", u8"配置"},
    {"custom", u8"自定义"},
    {"define", u8"设置"},
    {"delete", u8"删除"},
    {"dongle", u8"加密狗"},
    {"drives", u8"驱动器"},
    {"enable", u8"启用"},
    {"europe", u8"欧洲"},
    {"filter", u8"滤波"},
    {"finish", u8"完成"},
    {"floppy", u8"软盘"},
    {"height", u8"高度"},
    {"layers", u8"图层"},
    {"locked", u8"已锁定"},
    {"manual", u8"手册"},
    {"master", u8"主设备"},
    {"medium", u8"中速"},
    {"memory", u8"内存"},
    {"normal", u8"正常"},
    {"offset", u8"偏移"},
    {"os rom", u8"系统 ROM"},
    {"record", u8"录制"},
    {"region", u8"区域"},
    {"screen", u8"屏幕"},
    {"select", u8"选择"},
    {"stereo", u8"立体声"},
    {"system", u8"系统"},
    {"volume", u8"音量"},
    {"<dir>", u8"<目录>"},
    {"about", u8"关于"},
    {"audio", u8"音频"},
    {"blank", u8"消隐"},
    {"clock", u8"时钟"},
    {"color", u8"彩色"},
    {"cores", u8"核心列表"},
    {"debug", u8"调试"},
    {"drive", u8"驱动器"},
    {"eject", u8"弹出"},
    {"empty", u8"空"},
    {"japan", u8"日本"},
    {"layer", u8"图层"},
    {"lives", u8"生命数"},
    {"local", u8"本地"},
    {"model", u8"型号"},
    {"modem", u8"调制解调器"},
    {"mount", u8"挂载"},
    {"pause", u8"暂停"},
    {"press", u8"请按"},
    {"reset", u8"重置"},
    {"right", u8"右"},
    {"scale", u8"缩放"},
    {"sharp", u8"锐利"},
    {"slave", u8"从设备"},
    {"sound", u8"声音"},
    {"speed", u8"速度"},
    {"start", u8"开始"},
    {"synth", u8"合成器"},
    {"turbo", u8"加速"},
    {"video", u8"视频"},
    {"width", u8"宽度"},
    {"world", u8"世界"},
    {"auto", u8"自动"},
    {"back", u8"返回"},
    {"bank", u8"存储区"},
    {"baud", u8"波特率"},
    {"both", u8"两者"},
    {"cart", u8"卡带"},
    {"code", u8"代码"},
    {"core", u8"核心"},
    {"crop", u8"裁切"},
    {"disk", u8"磁盘"},
    {"done", u8"完成"},
    {"down", u8"下"},
    {"easy", u8"简单"},
    {"exit", u8"退出"},
    {"fast", u8"快速"},
    {"file", u8"文件"},
    {"full", u8"完整"},
    {"hard", u8"困难"},
    {"help", u8"帮助"},
    {"hq2x", u8"HQ2x"},
    {"left", u8"左"},
    {"link", u8"链路"},
    {"load", u8"加载"},
    {"menu", u8"菜单"},
    {"mode", u8"模式"},
    {"mono", u8"单声道"},
    {"mute", u8"静音"},
    {"none", u8"无"},
    {"play", u8"播放"},
    {"pri.", u8"主通道"},
    {"save", u8"保存"},
    {"sec.", u8"次通道"},
    {"slow", u8"慢速"},
    {"soft", u8"柔和"},
    {"stop", u8"停止"},
    {"sync", u8"同步"},
    {"tape", u8"磁带"},
    {"type", u8"类型"},
    {"all", u8"全部"},
    {"crt", u8"CRT"},
    {"eta", u8"剩余时间"},
    {"hue", u8"色相"},
    {"max", u8"最大"},
    {"min", u8"最小"},
    {"new", u8"新增"},
    {"off", u8"关闭"},
    {"usa", u8"美国"},
    {"yes", u8"是"},
    {"no", u8"否"},
    {"ok", u8"确认"},
    {"on", u8"开启"},
    {"up", u8"上"},
};
