name: build-mister

on:
  push:
    branches: [ master, cjk-osd ]   # 只要 master 就改成 [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # APT 源：amd64 走 archive/security；armhf 走 ports（避免 404）
      - name: Configure APT sources for multiarch
        run: |
          set -e
          sudo dpkg --add-architecture armhf
          sudo bash -c 'cat > /etc/apt/sources.list << "EOF"
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy main universe multiverse restricted
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy-updates main universe multiverse restricted
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy-backports main universe multiverse restricted
          deb [arch=amd64] http://security.ubuntu.com/ubuntu jammy-security main universe multiverse restricted
          deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports jammy main universe multiverse restricted
          deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports jammy-updates main universe multiverse restricted
          deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports jammy-backports main universe multiverse restricted
          deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports jammy-security main universe multiverse restricted
          EOF'
          sudo apt-get update

      - name: Install toolchains and deps
        run: |
          set -e
          sudo apt-get install -y \
            make pkg-config zip \
            gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
            libfreetype6-dev:armhf zlib1g-dev:armhf libpng-dev:armhf libbz2-dev:armhf

      # 某些 Makefile 写死了 arm-none- 前缀，做兼容别名
      - name: Add arm-none aliases (compat)
        run: |
          set -e
          for x in gcc g++ ar as ld strip objcopy objdump ranlib nm; do
            src="$(command -v arm-linux-gnueabihf-$x)"
            [ -n "$src" ] || { echo "missing arm-linux-gnueabihf-$x"; exit 1; }
            sudo ln -sf "$src" /usr/bin/arm-none-linux-gnueabihf-$x
          done

      - name: Build
        env:
          # 让 pkg-config 指向 armhf 的 .pc
          PKG_CONFIG_LIBDIR: /usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/share/pkgconfig
        run: |
          set -euo pipefail
          make clean || true

          # 单行赋值，避免换行截断
          FT_CFLAGS="$(pkg-config --cflags freetype2)"; FT_LIBS="$(pkg-config --libs freetype2)"
          CHDR_INC="-Ilib/libchdr/include -Ilib/libchdr"
          LZMA_INC="-Ilib/lzma -Ilib/lzma/C -Ilib/lzma/SDK/C"
          MINIZ_INC="-Ilib/miniz -Ilib/miniz/include"

          echo "FT_CFLAGS=${FT_CFLAGS}"
          echo "FT_LIBS=${FT_LIBS}"

          make -j"$(nproc)" \
            CROSS_COMPILE=arm-linux-gnueabihf- \
            CFLAGS="$CFLAGS $FT_CFLAGS -D_7ZIP_ST $CHDR_INC $LZMA_INC $MINIZ_INC" \
            CXXFLAGS="$CXXFLAGS $FT_CFLAGS -D_7ZIP_ST $CHDR_INC $LZMA_INC $MINIZ_INC" \
            CPPFLAGS="$CPPFLAGS $FT_CFLAGS -D_7ZIP_ST $CHDR_INC $LZMA_INC $MINIZ_INC" \
            LIBS="$LIBS $FT_LIBS" \
            LDLIBS="$LDLIBS $FT_LIBS"

      - name: Show result
        run: |
          file ./MiSTer || true
          ls -lh ./MiSTer || (echo "Build did not produce MiSTer binary" && exit 1)

      - name: Zip artifact
        run: zip -9 MiSTer-${{ github.ref_name }}-${{ github.sha }}.zip MiSTer

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiSTer-${{ github.ref_name }}
          path: |
            MiSTer
            MiSTer-*.zip
          retention-days: 14
