name: build-mister

on:
  push: { branches: [ master, cjk-osd ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps (armhf)
        run: |
          set -e
          sudo dpkg --add-architecture armhf
          sudo apt-get update
          sudo apt-get install -y \
            make pkg-config \
            gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
            libfreetype6-dev:armhf zlib1g-dev:armhf libpng-dev:armhf

      - name: Build
        env:
          # 让 pkg-config 查 armhf 的 .pc（而不是宿主 x86）
          PKG_CONFIG_LIBDIR: /usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/share/pkgconfig
        run: |
          set -e
          make clean || true
          FT_CFLAGS="$(pkg-config --cflags freetype2)"
          FT_LIBS="$(pkg-config --libs freetype2)"
          echo "freetype2 cflags: ${FT_CFLAGS}"
          echo "freetype2 libs:   ${FT_LIBS}"
          make -j"$(nproc)" \
            CFLAGS="$CFLAGS $FT_CFLAGS" \
            CXXFLAGS="$CXXFLAGS $FT_CFLAGS" \
            CPPFLAGS="$CPPFLAGS $FT_CFLAGS" \
            LIBS="$LIBS $FT_LIBS" \
            LDLIBS="$LDLIBS $FT_LIBS"

      - name: Upload MiSTer
        uses: actions/upload-artifact@v4
        with:
          name: MiSTer
          path: MiSTer
