name: build-mister

on:
  push: { branches: [ master, cjk-osd ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install cross toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf make

      - name: Build
        run: |
          make clean || true
          make -j"$(nproc)" CROSS_COMPILE=arm-linux-gnueabihf-

      - name: Upload MiSTer
        uses: actions/upload-artifact@v4
        with:
          name: MiSTer
          path: MiSTer
